# 1.LSA 간단 실습

In [1]:
import numpy as np
import pandas as pd

## 1.DTM 행렬 생성

In [2]:
A = np.array([[0,0,0,1,0,1,1,0,0],
              [0,0,0,1,1,0,1,0,0],
              [0,1,1,0,2,0,0,0,0],
              [1,0,0,0,0,0,0,1,1]])
print('DTM의 크기(shape) :', np.shape(A))
display(A)

DTM의 크기(shape) : (4, 9)


array([[0, 0, 0, 1, 0, 1, 1, 0, 0],
       [0, 0, 0, 1, 1, 0, 1, 0, 0],
       [0, 1, 1, 0, 2, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 1]])

## 2.Full SVD

- U

In [3]:
U, s,VT = np.linalg.svd(A, full_matrices=True)
print('행렬 U :',U.round(2))
print('행렬 U의 크기(shape) :',np.shape(U))

행렬 U : [[-0.24  0.75  0.   -0.62]
 [-0.51  0.44 -0.    0.74]
 [-0.83 -0.49 -0.   -0.27]
 [-0.   -0.    1.    0.  ]]
행렬 U의 크기(shape) : (4, 4)


- S
- linalg.svd()는 특이값 분해의 결과로 대각 행렬이 아닌 특이값의 리스트를 반환 따라서 다시 대각 행렬로 변환 해주어야 함.
- np.diag()는 1차원 array는 각각의 값을 대각 성분으로 가지는 대각 행렬 생성, 2차원은 대각 성분의 값을 추출

In [4]:
print('특이값 리스트 :',s)
print()

# 2차원행렬로 변환
print('2차원 행렬로 변환')
print(np.diag(s))
print('특이값 리스트의 크기(shape) :',np.shape(s))

특이값 리스트 : [2.68731789 2.04508425 1.73205081 0.77197992]

2차원 행렬로 변환
[[2.68731789 0.         0.         0.        ]
 [0.         2.04508425 0.         0.        ]
 [0.         0.         1.73205081 0.        ]
 [0.         0.         0.         0.77197992]]
특이값 리스트의 크기(shape) : (4,)


In [5]:
# 원본에 맞춰서 4x9 배열 생성
S = np.zeros((4,9))
print(S)
print()

# 특이값을 대각행렬에 삽입
S[:4,:4] = np.diag(s)
print(S)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[[2.68731789 0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         2.04508425 0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         1.73205081 0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.77197992 0.         0.
  0.         0.         0.        ]]


- VT

In [6]:
VT = VT.T
print('행렬 VT :')
print(VT.round(2))
print('행렬 VT의 크기(shape) :',np.shape(VT))

행렬 VT :
[[-0.    0.    0.58  0.   -0.   -0.29 -0.29 -0.5  -0.5 ]
 [-0.31 -0.24 -0.   -0.35 -0.78  0.31 -0.1  -0.06 -0.06]
 [-0.31 -0.24  0.   -0.35 -0.01 -0.78  0.26  0.15  0.15]
 [-0.28  0.58  0.    0.16 -0.2  -0.24 -0.59  0.24  0.24]
 [-0.8  -0.26 -0.    0.25  0.4   0.23 -0.08 -0.05 -0.05]
 [-0.09  0.37  0.   -0.8   0.4   0.23 -0.08 -0.05 -0.05]
 [-0.28  0.58 -0.    0.16 -0.2   0.01  0.66 -0.19 -0.19]
 [-0.   -0.    0.58 -0.    0.    0.14  0.14  0.75 -0.25]
 [-0.   -0.    0.58 -0.    0.    0.14  0.14 -0.25  0.75]]
행렬 VT의 크기(shape) : (9, 9)


- U X S X VT = A
- np.allclose() : 두 배열이 거의 같은지 확인

In [7]:
# 민감한 소수점 문제 무시해줌
np.allclose(A, np.dot(np.dot(U,S),VT).round(2))

False

## 3.Truncated SVD

In [8]:
# 특이값 상위 2개만 보존
S_T = S[:2,:2]
print('대각 행렬 S')
print(S_T.round(2))


대각 행렬 S
[[2.69 0.  ]
 [0.   2.05]]


In [9]:
U_T = U[:,:2]
print('행렬 U')
print(U_T.round(2))

행렬 U
[[-0.24  0.75]
 [-0.51  0.44]
 [-0.83 -0.49]
 [-0.   -0.  ]]


In [10]:
VT_T = VT[:2]
print('직교행렬VT')
print(VT_T.round(2))

직교행렬VT
[[-0.    0.    0.58  0.   -0.   -0.29 -0.29 -0.5  -0.5 ]
 [-0.31 -0.24 -0.   -0.35 -0.78  0.31 -0.1  -0.06 -0.06]]


In [11]:
A_prime = np.dot(U_T, np.dot(S_T, VT_T)).round(2)
print(A)
print(A_prime)

[[0 0 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0]
 [1 0 0 0 0 0 0 1 1]]
[[-0.47 -0.37 -0.37 -0.54 -1.2   0.66  0.03  0.23  0.23]
 [-0.28 -0.22 -0.79 -0.32 -0.71  0.68  0.3   0.63  0.63]
 [ 0.31  0.24 -1.29  0.35  0.78  0.33  0.75  1.17  1.17]
 [ 0.    0.   -0.    0.    0.    0.    0.    0.    0.  ]]


## 4.sklearn TruncatedSVD 활용

In [12]:
from sklearn.decomposition import TruncatedSVD
# TruncatedSVD 객체 생성
svd_model = TruncatedSVD(n_components=2,
                         algorithm='randomized',
                         random_state=42)

# 문서-토픽 행렬 생성 UxS
las_matrix = svd_model.fit_transform(A)

# 단어-토픽 행렬 (components_) VT
components = svd_model.components_

- **fit_transform**은 문서-토픽 행렬을 반환. U x S
      - 행(n_samples): 이 행렬의 각 행은 하나의 문서를 나타냄.
      - 열(n_components): 이 행렬의 각 열은 하나의 토픽(축소된 차원)을 나타냄.
      - 각 값: 특정 문서가 특정 토픽에서 얼마나 설명되는지를 나타냄. 값이 클수록 그 문서가 해당 토픽에서 더 잘 설명된다는 의미.

- **components_**는 토픽-단어 행렬. S x VT
      - 행(n_components): 토픽을 나타냄.
      - 열(n_features): 단어를 나타냄.
      - 각 값: 특정 토픽에서 특정 단어의 가중치(기여도)를 나타냄.



In [13]:
# 출력
print('문서-토픽 행렬')
print(las_matrix.round(2))
print()

print('단어-토픽 행렬')
print(components.round(2))
print()

# 원래 행렬 근사
A_prime = np.dot(las_matrix, components).round(2)
print('토픽 행렬')
print(A_prime)
print()

print('원래 행렬')
print(A)

문서-토픽 행렬
[[ 0.64  1.54]
 [ 1.36  0.91]
 [ 2.23 -1.  ]
 [ 0.   -0.  ]]

단어-토픽 행렬
[[ 0.    0.31  0.31  0.28  0.8   0.09  0.28  0.    0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]]

토픽 행렬
[[ 0.   -0.17 -0.17  1.08  0.12  0.62  1.08 -0.   -0.  ]
 [ 0.    0.2   0.2   0.91  0.86  0.45  0.91  0.    0.  ]
 [ 0.    0.93  0.93  0.03  2.05 -0.17  0.03  0.    0.  ]
 [ 0.    0.    0.    0.    0.   -0.    0.    0.    0.  ]]

원래 행렬
[[0 0 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0]
 [1 0 0 0 0 0 0 1 1]]


# 2.뉴스 데이터를 통한 LSA 분석
- 사이킷런에서는 Twenty Newsgroups이라고 불리는 20개의 다른 주제를 가진 뉴스그룹 데이터를 제공

## 1.필요 모듈 로드

In [14]:
import pandas as pd
from sklearn.datasets import fetch_20newsgroups
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

## 2.데이터 로드

In [15]:
dataset = fetch_20newsgroups(shuffle=True, random_state=42, remove=('headers', 'footers', 'quotes'))
documents = dataset.data
print('샘플의 수 :',len(documents))

샘플의 수 : 11314


In [16]:
documents[0]

'I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.'

In [17]:
print(dataset.target_names)
print("뉴스 카테고리의 수 : ", len(dataset.target_names))

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']
뉴스 카테고리의 수 :  20


## 3.데이터 전처리
  1. 대문자->소문자
  2. 구두점, 숫자, 특수 문자 제거
  3. 짧은 단어 제거

- [^a-zA-Z] : 영문자를 제외한 모든 문자
- regrex=True : 함수에서 이 패턴을 정규 표현식으로 처리
- ' '.join([w for w in x.split() if len(w)>3]) : 데이터를 순회하면서 공백으로 단어를 나누고 길이가 3이상인 단어들을 리스트로 반환하고 join 함수를 통해서 한 줄의 텍스트로 병합

In [18]:
news_df = pd.DataFrame({'document' : documents})
news_df['document'].apply(lambda x: [w for w in x.split() if len(w)>3])

0        [wondering, anyone, there, could, enlighten, t...
1        [fair, number, brave, souls, upgraded, their, ...
2        [well, folks,, plus, finally, gave, ghost, thi...
3        [have, Weitek's, address/phone, number?, like,...
4        [From, article, <C5owCB.n3p@world.std.com>,, t...
                               ...                        
11309    [From:, nyeda@cnsvax.uwec.edu, (David, Nye), n...
11310    [have, (very, old), 512k, Plus,, both, which, ...
11311    [just, installed, DX2-66, clone, motherboard,,...
11312    [Wouldn't, this, require, hyper-sphere., 3-spa...
11313    [Stolen, from, Pasadena, between, 4:30, 6:30, ...
Name: document, Length: 11314, dtype: object

In [19]:
news_df = pd.DataFrame({'document':documents})
# 특수 문자 제거
news_df['clean_doc'] = news_df['document'].str.replace('[^a-zA-Z]',' ',regex=True)

# 길이가 3이하인 단어는 제거 (길이가 짧은 단어 제거)
news_df['clean_doc'] = news_df['clean_doc'].apply(lambda x: ' '.join([w for w in x.split() if len(w)>3]))

# 전체 단어에 대한 소문자 변환
news_df['clean_doc'] = news_df['clean_doc'].apply(lambda x: x.lower())

news_df['clean_doc']

0        wondering anyone there could enlighten this ot...
1        fair number brave souls upgraded their clock o...
2        well folks plus finally gave ghost this weeken...
3        have weitek address phone number like some inf...
4        from article owcb world tombaker world baker u...
                               ...                        
11309    from nyeda cnsvax uwec david neurology consult...
11310    have very plus both which have same problem th...
11311    just installed clone motherboard tried mountin...
11312    wouldn this require hyper sphere space points ...
11313    stolen from pasadena between blue white honda ...
Name: clean_doc, Length: 11314, dtype: object

## 4.TF-IDF 벡터화

- stop_words='english' : 불용어 사전, sklearn에서 제공하는 기본 영어 불용어 리스트
- max_features=1000 : 상위 1000개의 단어만을 보존
- max_df=0.5 : 너무 자주 등장하는 경우 해당 단어를 무시. 50% 이상 나타나는 단어는 무시
- smooth_idf=True : IDF 점수 계산 시, smoothing을 적용.
  - 스무딩은 IDF 계산에서 모든 문서에 1을 더하는 방식으로, IDF 값이 0이 되는 것을 방지. 즉 적절한 IDF 값을 가지게 하고 안정적인 결과를 얻을 수 있음

In [20]:
# TF-IDF 행렬의 크기 확인
vectorizer = TfidfVectorizer(stop_words='english',
                             max_features=1000, # 상위 1000개 단어만 보존
                             max_df=0.5,
                             smooth_idf=True) # idf값이 0이 되지 않게 1을 더해주는 것

X = vectorizer.fit_transform(news_df['clean_doc'])

print('TF-IDF 행렬의 크기 :',X.shape)

TF-IDF 행렬의 크기 : (11314, 1000)


## 5.LSA를 통한 토픽 모델링

In [21]:
svd_model = TruncatedSVD(n_components=20,
                        algorithm='randomized',
                        n_iter=100,
                        random_state=42)
svd_model.fit(X)
len(svd_model.components_)

20

In [22]:
np.shape(svd_model.components_)

(20, 1000)

In [23]:
svd_model.components_

array([[ 0.01409818,  0.04787982,  0.02051048, ...,  0.07483329,
         0.01377606,  0.01712888],
       [-0.00521437,  0.01742255, -0.01542793, ..., -0.06266609,
        -0.01075043, -0.01888594],
       [ 0.00243598, -0.00142246, -0.01848973, ...,  0.05823359,
         0.02412148,  0.02038499],
       ...,
       [ 0.00746824, -0.00689738, -0.00963879, ..., -0.03316437,
        -0.00649624, -0.0002525 ],
       [ 0.00352545,  0.01029423, -0.01284824, ...,  0.01336511,
        -0.01588696, -0.00127575],
       [-0.00221752,  0.00855738,  0.00623431, ..., -0.05112382,
        -0.00794478, -0.00491315]])

- argsort() : 배열의 인덱스를 정렬된 순서로 반환 [3,1,2] -> [1,2,0] (오름차순 정렬)
- [::-1][:5] : 역순으로 정렬 후 5개의 데이터 선택

In [24]:
example_array = np.array([[0.1, 0.4, 0.2, 0.9, 0.3]])
print("argmax : ", example_array.argmax())

# 가장 높은 가중치를 가진 값들 확인
sorted_indices = example_array.argsort()[0][::-1][:5]
print(sorted_indices)

argmax :  3
[3 1 4 2 0]


- 주제0번에 대한 단어별 가중치

In [25]:
print(svd_model.components_[0])
print(svd_model.components_[0].shape)

[0.01409818 0.04787982 0.02051048 0.02933549 0.01732167 0.01227351
 0.01648381 0.01181282 0.01084788 0.0593574  0.01055266 0.0111863
 0.00867278 0.03419897 0.01132049 0.0401397  0.0177775  0.00850201
 0.03508718 0.0158544  0.02076485 0.01292826 0.01060273 0.01168965
 0.01392965 0.02813562 0.0110224  0.00927105 0.00607689 0.0090752
 0.03507546 0.01364729 0.01940152 0.04266487 0.01638954 0.0120186
 0.01376949 0.02842646 0.02492808 0.01559292 0.01259682 0.021828
 0.03209353 0.01136994 0.01236091 0.01826516 0.01198612 0.00833366
 0.03061078 0.01221436 0.02441905 0.02483554 0.01177919 0.00769201
 0.0165582  0.01614453 0.01055487 0.01213478 0.03688943 0.01293101
 0.02388438 0.02126642 0.02266981 0.01389217 0.01078975 0.01070881
 0.01389446 0.0098783  0.01064283 0.01166813 0.05015364 0.01938976
 0.01583951 0.04028201 0.01072811 0.01719875 0.02045526 0.03970562
 0.01404409 0.01610265 0.01334269 0.01173088 0.01054992 0.01465089
 0.01299643 0.07890412 0.05921976 0.07381847 0.03534568 0.03939203


In [26]:
svd_model.components_.argsort()[0][::-1][:5]

array([448, 483, 458, 626, 893])

In [27]:
(vectorizer.get_feature_names_out()[448],svd_model.components_[0][448].round(5))

('just', 0.20887)

In [28]:
(vectorizer.get_feature_names_out()[483],svd_model.components_[0][483].round(5))

('like', 0.20469)

In [29]:
terms = vectorizer.get_feature_names_out() # 단어 집합. 1,000개의 단어가 저장됨.
for idx, topic in enumerate(svd_model.components_):
    # 각 토픽에 대해 상위 5개의 단어와 그 단어의 값을 추출
    sorted_indices = topic.argsort()[::-1][:5]  # 내림차순으로 상위 5개 단어의 인덱스 추출
    print("Topic %d:" % (idx+1), [(terms[i], topic[i].round(5)) for i in sorted_indices])
    break  # 첫 번째 토픽만 출력하기 위해 break

Topic 1: [('just', 0.20887), ('like', 0.20469), ('know', 0.19349), ('people', 0.18318), ('think', 0.1697)]


In [30]:
def get_topics(components, feature_names, n=5):
    for idx, topic in enumerate(components):
        print("Topic %d:"%(idx+1),
              [(feature_names[i], topic[i].round(5))for i in topic.argsort()[::-1][:5]])

get_topics(svd_model.components_,terms)

Topic 1: [('just', 0.20887), ('like', 0.20469), ('know', 0.19349), ('people', 0.18318), ('think', 0.1697)]
Topic 2: [('thanks', 0.32763), ('windows', 0.28786), ('card', 0.18019), ('drive', 0.16864), ('mail', 0.15261)]
Topic 3: [('game', 0.34011), ('team', 0.30311), ('year', 0.26894), ('games', 0.23784), ('drive', 0.17472)]
Topic 4: [('drive', 0.46159), ('scsi', 0.17188), ('disk', 0.14451), ('hard', 0.13805), ('problem', 0.12763)]
Topic 5: [('drive', 0.39993), ('know', 0.28768), ('thanks', 0.24917), ('does', 0.24678), ('just', 0.17387)]
Topic 6: [('just', 0.55559), ('like', 0.23559), ('windows', 0.23078), ('know', 0.15795), ('does', 0.11156)]
Topic 7: [('just', 0.43264), ('like', 0.22858), ('mail', 0.15052), ('bike', 0.11698), ('thanks', 0.10025)]
Topic 8: [('does', 0.39692), ('know', 0.25192), ('chip', 0.22492), ('like', 0.17824), ('card', 0.15695)]
Topic 9: [('like', 0.42065), ('card', 0.32249), ('sale', 0.20267), ('video', 0.1571), ('offer', 0.14119)]
Topic 10: [('like', 0.61166), ('

In [31]:
def get_document_topics(lsa_matrix, n=5):
    for idx, doc in enumerate(las_matrix):
        if idx==10 :break
        print(f"Document {idx+1}:", [(f"Topic {i+1}", doc[i].round(5)) for i in doc.argsort()[::-1][:n]])

# 문서별 토픽 비율 확인
lsa_matrix = svd_model.transform(X)

# 함수 호출
get_document_topics(lsa_matrix, n=5)


Document 1: [('Topic 2', 1.53603), ('Topic 1', 0.64429)]
Document 2: [('Topic 1', 1.35999), ('Topic 2', 0.90808)]
Document 3: [('Topic 1', 2.22643), ('Topic 2', -0.99919)]
Document 4: [('Topic 1', 0.0), ('Topic 2', -0.0)]
